field/urls.py
from django.urls import path, include

from . import views

app_name = "field"

urlpatterns = [
    path("", views.config, name="config"),
    path("<str:field_name>", views.config, name="config"),
]

pages/urls.py
from django.urls import path, include

from . import views

app_name = "pages"

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("signup/", views.user_signup, name="signup"),
    path("make-scaffold/", views.make_scaffold, name="make-scaffold"),
    path("heck/", views.what_the_heck, name="what-the-heck"),
]

templates/partials/_footer.html
<footer>
    <div class="row d-flex justify-content-center footer">
        <div class="col-12">
            <span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">SongScaffolder</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="http://www.jonofoz.com" property="cc:attributionName" rel="cc:attributionURL">Jon Korte</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>. <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a>
        </div>
    </div>
</footer>

templates/partials/_header.html
<div class="container">
    <div class="jumbtron text-center">
        <div class="row">
            <div class="col-md-2 text-center"></div>
            <div class="col-md-8 text-center"><a href="{% url 'pages:index' %}" class="logo-link"><h1 class="display-4 logo text-center">SongScaffolder</h1></a></div>
            <div class="col-md-2 text-center"></div>
        </div>
        <div class="row">
            <div class="col-12" id="slogan"><em>When you just gotta generate randomized song ideas!</em></div>
        </div>
    </div>
</div>
<br>

templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light">
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="hello-user tilt d-none d-lg-block">{% if user.is_authenticated %} (Hi, {{ user.username }}!) {% endif %}</div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <a class="nav-link text-right" href="{% url 'pages:index' %}"> <span class="sr-only">(current)</span> Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-right" href="#">Site Settings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-right" href="{% url 'pages:logout' %}">Logout</a>
            </li>
            <li class="nav-item">
                <div class="hello-user d-block d-lg-none text-center">{% if user.is_authenticated %} (Hi, {{ user.username }}!) {% endif %}</div>
            </li>
        </ul>
    </div>
</nav>

templates/partials/_save-config.html
<div class="row">
    <div class="col-6">
        <button class="btn btn-lg btn-block btn-confirm button-save" aria-pressed="true">Save Changes</a>
    </div>
    <div class="col-6">
        <button class="btn btn-lg btn-block btn-grey button-delete-all" aria-pressed="true">Delete All</a>
    </div>
</div>