field/urls.py
from django.urls import path, include

from . import views

app_name = "field"

urlpatterns = [
    path("", views.config, name="config"),
    path("<str:field_name>", views.config, name="config"),
]

pages/urls.py
from django.urls import path, include

from . import views

app_name = "pages"

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("signup/", views.user_signup, name="signup"),
    path("make-scaffold/", views.make_scaffold, name="make-scaffold"),
    path("heck/", views.what_the_heck, name="what-the-heck"),
]

templates/pages/config.html
{% extends 'base.html' %}

{% load _extras %}

{% block title %}
{{ ""|replace_dashes:field_name|title }}
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}

{% block content %}

<h1 class="text-center config-header">{{ ""|replace_dashes:field_name|title }}</h1>
<hr>

<div id="save-delete-1">
    {% include 'partials/_save-config.html' %}
</div>
<br>
<br>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
          <th id="col-header-entry" class="text-center" scope="col"><p>What to include</p></th>
          <th id="col-header-frequency" class="text-center" scope="col"><p>How often it's chosen</p></th>
          <th id="col-header-delete" class="text-center" scope="col"><p>delet this</p></th>
        </tr>
      </thead>
    <tbody>
        {% for k, v in field_data.items %}
        <!-- Replace with slugify I believe -->
            {% with "tr-"|addstr:k as dynamic_id %}
                <tr class="config-row">
                    <td style="width: 70%;"><input type="text" class="config-input-item no-border border-bottom field-form inherit-bg-color" placeholder="Edit Me!" value="{{ k }}"></input></td>
                    <td class="text-center d-flex justify-content-center">
                        <ul class="pagination">
                            {% for i in "012345"|make_list %}
                                <li class="d-none d-md-flex field-item {% if i == ''|addstr:v  %}active{% endif %}"><p class="page-link" href="#">{{ i }}</p></li>
                            {% endfor %}
                        </ul>
                        <li class="d-flex d-md-none"></li><input type="text" class="config-input-quantity no-border border-bottom field-form inherit-bg-color d-flex d-md-none text-center" placeholder="0-5" value="{{ v }}"></input></li>
                    </td>
                    <td style="width: 10%;">
                        <a href="#" class="d-none d-md-flex btn btn-secondary btn-grey row-deleter active justify-content-center" role="button" aria-pressed="true">Delete</a>
                        <a class="d-flex d-md-none row-deleter" role="button"><i class="fa fa-times-circle"></i></a>
                    </td>
                </tr>
            {% endwith %}
        {% endfor %}
    </tbody>
</table>

<div class="row">
    <div class="col-12 col-md-9">
        <button class="btn btn-primary btn-confirm btn-block" id="button-add-rows">+</button>
    </div>
    <div id="add-rows-spacer">
        <br>
    </div>
    <div class="col-12 col-md-3 text-center">
        <label id="label-for-n-rows" for="how-many-to-add">Add this many new rows</label>
        <input type="text" id="how-many-to-add" class="no-border border-bottom field-form text-center" placeholder=1>
    </div>
</div>
<br>
<br>
<div id="save-delete-2">
    {% include 'partials/_save-config.html' %}
</div>

<!-- Eventually I want to remove this call to jQuery, since I think it should only be done in base.html.  -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

<script>
    tbody = $('tbody')
    function addItem(){
        $('tbody').append(`
            <tr class="config-row">
                <td style="width: 70%;"><input type="text" class="config-input-item no-border border-bottom field-form inherit-bg-color" placeholder="Edit Me!"></input></td>
                <td class="text-center d-flex justify-content-center">
                    <ul class="pagination">
                        {% for i in "012345"|make_list %}
                            <li class="d-none d-md-flex field-item {% if i == '3' %}active{% endif %}"><p class="page-link" href="#">{{ i }}</p></li>
                        {% endfor %}
                    </ul>
                    <li class="d-flex d-md-none"></li><input type="text" class="config-input-quantity no-border border-bottom field-form inherit-bg-color d-flex d-md-none text-center" placeholder="0-5" value="3"></input></li>
                </td>
                <td style="width: 10%;">
                    <a href="#" class="d-none d-md-flex btn btn-secondary btn-grey row-deleter active justify-content-center" role="button" aria-pressed="true">Delete</a>
                    <a class="d-flex d-md-none row-deleter" role="button"><i class="fa fa-times-circle"></i></a>
                </td>
            </tr>
        `)
    }
</script>

<script>
    colHeaderFreq = $("#col-header-frequency");
    colHeaderDelete = $("#col-header-delete");
    labelRows = $("#label-for-n-rows");
    addRowsSpacer = $("#add-rows-spacer");
    table = $("table");
    function checkScreenSize(){
        if (screen.width < 768){
            colHeaderFreq.html("<p>Freq.</p>");
            colHeaderDelete.html("<p>Del.</p>");
            addRowsSpacer.show();
        }
        else{
            colHeaderFreq.html("<p>How often it's chosen</p>");
            colHeaderDelete.html("<p>delet this</p>");
            addRowsSpacer.hide();
        }
    }

    function checkWhatShouldBeDisplayed(){
        tableRowCount = $("td").length / 3
        if (tableRowCount > 0) {
            table.show()
        }
        else {
            table.hide()
        }
        saveDeleteRow = $("#save-delete-2")
        if (tableRowCount >= 5){
            saveDeleteRow.show()
        }
        else {
            saveDeleteRow.hide()
        }
    }

    $(document).ready( function() {
        checkWhatShouldBeDisplayed();
        checkScreenSize();
    })

    $(window).resize(function() {
        checkScreenSize();
    });

    $(document).on("click", ".button-delete-all", function() {
        $(".config-row").remove()
        checkWhatShouldBeDisplayed()
        return false
    })
    $(document).on("click", ".row-deleter", function() {
        $(this).parent().parent().remove()
        checkWhatShouldBeDisplayed()
        return false
    })

    function setActive(item){
        LIs = item.parent().children()
        for (i = 0; i < LIs.length; i++){
            LIs[i].classList.remove("active")
        }
        item.addClass("active")
    }
    $(document).on("click", ".field-item", function() {
        setActive($(this))
        // Set the equivalent input to the same value.
        $(this).parent().parent().children("input").val($(this).text())
        return false
    });
    $(document).on("input", ".config-input-quantity", function() {
        // Set the equivalent pagination to the same value.
        setActive($(this).parent().children("ul").children().filter(`:nth-child(${parseInt($(this).val())+1})`));
        return false
    });

    $(document).on("click", ".button-save", function(){
        configRows = $('.config-row')
        newConfigData = {}
        for (i=0; i < configRows.length; i++){
            key = configRows[i].children[0].children[0].value
            value = 3
            for (j=0; j < configRows[i].children[1].children[0].children.length; j++) {
                if (configRows[i].children[1].children[0].children[j].className.includes("active")){
                    value = j
                }
            }
            newConfigData[key] = value
        }
        $.ajax({
            type: "POST",
            url: "{% url 'field:config' field_name %}",
            dataType: "json",
            data: {
                "field_data": JSON.stringify(newConfigData),
            },
            success: function(){
                top.location.href = "{% url 'pages:login' %}"
            },
            failure: function(){
                top.location.href = "{% url 'pages:login' %}"
            },
            error: function(){
                top.location.href = "{% url 'pages:login' %}"
            },
        })
    })

    $("#button-add-rows").on("click", function() {
        howMany = $("#how-many-to-add")
        numRowsToAdd = howMany.val() != "" ? parseInt(howMany.val()) : 1;
        for (i=0; i < numRowsToAdd; i++) {
            addItem();
        }
        checkWhatShouldBeDisplayed();
    });
</script>

{% endblock %}

templates/pages/index.html
{% extends 'base.html' %}

{% block title %}
SongScaffolder
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-4 header-col">
            <!-- <div class="p-2 text-center"><em>Fields.</em></div> -->
            <div class="p-2 lead text-center" id="header-for-fields" >Use + Randomize These!</div>
        </div>
        <div class="col-4 header-col">
            <!-- <div class="p-2 text-center"><em>Quantities.</em></div> -->
            <div class="p-2 lead text-center" id="header-for-quantities" >I Want This Many.</div>
        </div>
        <div class="col-4 header-col">
            <!-- <div class="p-2 text-center"><em>Specs.</em></div> -->
            <div class="p-2 lead text-center" id="header-for-specifications" >I Define Them Here.</div>
        </div>
    </div>
    <hr>
    <section>
        <div class="row get-help-row">
            <div class="col-md-4 col-6 first-col">
                <p class="get-help h3 text-center" id="get-help-for-fields">
                    <i class="fa fa-question-circle" class="get-help h3 text-center" data-toggle="tooltip" data-placement="right" data-html="true" title="Checking these will include random selections of the corresponding field into the scaffold. These selections can be specified by clicking the appropriate <a class='fa fa-list fa-list-tooltip'></a> button." id="get-help-with-randomizing_{{ field.id }}"></i>
                </p>
            </div>
            <div class="col-md-4 col-3 second-col">
                <p class="get-help h3 text-center" id="get-help-for-quantities">
                    <i class="fa fa-question-circle" data-toggle="tooltip" data-placement="right" title="These determine how many items from the corresponding field should be included in the scaffold."></i>
                </p>
            </div>
            <div class="col-md-4 col-3 third-col">
                <p class="get-help h3 text-center" id="get-help-for-specifications">
                    <i class="fa fa-question-circle" data-toggle="tooltip" data-placement="right" title="Clicking these will allow you to specify the selections for the corresponding field."></i>
                </p>
            </div>
        </div>
    </section>

    {% if fields %}
        {% for field in fields %}

            <div class="row first-row">
            <!-- 1: The field name, the switch for it, and an info bubble -->
                <!-- Medium+ displays -->
                <div class="d-none d-md-block col-4 first-col">
                    <div class="row">
                        <div class="col-md-7 text-center">
                            <p>{{ field.title }}</p>
                        </div>
                        <div class="col-md-5">
                            <label class="switch">
                                <input type="checkbox" class="field-switch" id="switch-include_{{ field.id }}" tabindex=0>
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                </div>
                <!-- Small- displays -->
                <div class="d-flex d-md-none col-6 first-col">
                    <div class="container-fluid btn-div">
                        <input type="button" class="btn btn-green btn-block btn-off" id="button-include_{{ field.id }}" value="{{ field.title }}" tabindex=0>
                    </div>
                </div>
            <!-- 2: The quantity form for the field -->
                <div class="col-3 col-md-4 second-col d-flex justify-content-center">
                    <form>
                        <input type="text" class="no-border border-bottom text-center field-form" id="quantity-for_{{ field.id }}" placeholder=1><br><br>
                    </form>
                </div>
            <!-- 3: The specs and an info bubble for what they do -->
                <div class="col-3 col-md-4 third-col d-flex justify-content-center">
                    <div><a class="fa fa-list" id="define-specs-for_{{ field.id }}" href="{% url 'field:config' field.id %}"></a></div>
                </div>
            </div>


        {% endfor %}
    {% endif %}
    <br>
    <br>
    <br>
    <div class="row">
        <div class="col-2">
        </div>
        <div class="col-8">
            <button class="btn btn-lg btn-block btn-confirm" id="btn-make-scaffold" data-toggle="modal" data-target=".bd-example-modal-lg">SCAFFOLD THAT SONG</button>
        </div>
        <div class="col-2">
        </div>
    </div>

    <div class="container-fluid">
    <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="jumbotron">
                    <h4 id="scaffold-quote" class="display-4 text-center"></h4>
                    <table class="table table-striped">
                        <tbody>

                        </tbody>
                    </table>
                    <div id="section-scaffold-modal-buttons"></div>
                </div>
            </div>
        </div>
    </div>

    <!-- Eventually I want to remove this call to jQuery, since I think it should only be done in base.html.  -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

    <script>
        // onMediumScreen = screen.width < 768 ? true : false

        $("input[id^='button-include_']").on("click", function() {
            elementButton = $(this);
            elementButton.toggleClass("btn-off");
            elementSwitch = $(`#switch-include_${elementButton.attr("id").split("_")[1]}`)
            elementSwitch.prop("checked", elementButton.attr("class").includes("btn-off") ? false : true);
        });
        $("input[id^='switch-include_']").on("click", function() {
            elementSwitch = $(this);
            checked = elementSwitch.prop("checked")
            elementButton = $(`#button-include_${elementSwitch.attr("id").split("_")[1]}`)
            if (checked == true && elementButton.attr("class").includes("btn-off") == true){
                elementButton.toggleClass("btn-off");
            }
            else if (checked == false && elementButton.attr("class").includes("btn-off") == false){
                elementButton.toggleClass("btn-off");
            }
        });

        $("#btn-make-scaffold").on("click", function() {
            // For fun, we have nice quotes. :)
            scaffoldQuotes = [
                "Take it and run!",
                "You <em>can</em> make the thing!",
                "Make it tasty!",
                "Don't forget the sauce!",
                "Make parental figures proud!",
                "You were born for this!",
                "Never stop not stopping!",
                "We have liftoff!",
                "And GO!",
                "3,2,1, L E T ' S 🎷 J A M",
                "Carry that weight!",
            ];
            // First, we'll clear any old scaffold results.
            tbody = $("tbody");
            sectionWTH = $("#section-scaffold-modal-buttons");
            scaffoldQuote = $("#scaffold-quote");
            tbody.children().remove();
            sectionWTH.children().remove();
            scaffoldQuote.html("");

            directives = {}
            switches = $("input[id^='switch-include_']").filter(":visible");
            buttons  = $("input[id^='button-include_']").filter(":visible");
            onMediumScreen = true ? buttons.length > 0 : false;

            // There's no point in pinging the backend if no field was selected: we assume this is so, at first!
            atLeastOneFieldSelected = false;

            quantities = $(`input[id^="quantity-for_"]`).filter(":visible");
            for (i = 0; i < quantities.length; i++) {
                fieldName = quantities[i].id.split("_")[1];
                quantityForm = $(`input[id^="quantity-for_${fieldName}"]`);
                fieldValue = quantityForm.val() != "" ? parseInt(quantityForm.val()) : 1;
                if (onMediumScreen) {
                    if (!(buttons[i].getAttribute("class").includes("btn-off"))){
                        directives[fieldName] = {
                            "include": true,
                            "quantity": fieldValue
                        }
                        atLeastOneFieldSelected = true;
                    }
                    else {
                        directives[fieldName] = {
                            "include": false
                        }
                    }
                }
                else {
                    if (switches[i].checked == true){
                        directives[fieldName] = {
                            "include": true,
                            "quantity": fieldValue
                        }
                        atLeastOneFieldSelected = true;
                    }
                    else {
                        directives[fieldName] = {
                            "include": false
                        }
                    }
                }
            }
            if (atLeastOneFieldSelected) {
                console.log(directives)
                $.ajax({
                    type: "POST",
                    url: "{% url 'pages:make-scaffold' %}",
                    dataType: "json",
                    data: {
                        "directives": JSON.stringify(directives),
                        "use_title_case": true
                    },
                    success: function(data){
                        for (const [key, value] of Object.entries(data)){
                            tbody.append(
                                `
                                    <tr>
                                        <td>${key}</td>
                                        <td>${value.join(', ')}</td>
                                    </tr>
                                `
                            );
                        }

                        result = data
                        thereWasUndefinedData = false;
                        for (field in data) {
                            if (data[field][0].startsWith("UNDEFINED:")){
                                thereWasUndefinedData = true;
                            }
                        }
                        if (thereWasUndefinedData){
                            scaffoldQuote.html("There were some problems...")
                        }
                        else {
                            scaffoldQuote.html(scaffoldQuotes[Math.floor(Math.random() * scaffoldQuotes.length)])
                        }
                        $("#section-scaffold-modal-buttons").append(
                            `
                                <br>
                                <div class="row">
                                    <div class="col-6 justify-content-center">
                                        <button class="btn btn-grey btn-block btn-small" id="btn-what-the-heck" onclick="location.href={% url 'pages:what-the-heck' %};"> What the heck?</button>
                                    </div>
                                    <div class="col-6 justify-content-center">
                                        <button class="btn btn-green btn-block btn-small btn-confirm" data-dismiss="modal">OK!</button>
                                    </div>
                                </div>
                            `)
                    },
                    failure: function(data){
                        scaffoldQuote.html("Hmm...")
                        tbody.append(
                            `
                                <tr>
                                    <td>There was a failure.</td>
                                    <td>We're not sure why.</td>
                                </tr>
                            `
                        )
                    },
                    error: function(xhr, status, error){
                        scaffoldQuote.html("🤯")
                        var errorMessage = xhr.status + ': ' + xhr.statusText
                        tbody.append(
                            `
                                <tr>
                                    <td>There was an error:</td>
                                    <td>${errorMessage}</td>
                                </tr>
                            `
                        )
                    }
                });
            }
            else {
                scaffoldQuote.html("Whoops 🔌")
                tbody.append(
                    `
                        <tr>
                            <td>You selected nothing!</td>
                            <td>Please select at least one field to include.</td>
                        </tr>
                    `
                )
                $("#section-scaffold-modal-buttons").append(
                    `
                        <br>
                        <div class="row">
                            <div class="col-12 justify-content-center">
                                <button class="btn btn-green btn-block btn-small btn-confirm" data-dismiss="modal">Ah snap</button>
                            </div>
                        </div>
                    `
                )
            }
        });
    </script>
{% endblock %}

templates/pages/what-the-heck.html
{% extends 'base.html' %}

{% block title %}
What The Heck
{% endblock %}

{% block content %}
    <div class="container">
        <div class="jumbotron">
            <div class="row">
                <div class="col-12 d-flex justify-content-center">
                    <h1 class="display-4">Ah yes, vague results.</h1>
                </div>
            </div>
            <div class="row">
                <div class="col-12 d-flex justify-content-center">
                    <p class="lead">We can explain. 😁</p>
                </div>
            </div>
        </div>
        <section>
            <p>"What do my vague results even mean?" you ask. "How do I make sense of them??"</p>
            <p>Good question. To understand, we must assume your goal is <strong>to write a song</strong> and that you're <strong>looking for a place to start.</strong></p>
            <p style="font-size: 1.5em;"><strong>💥BAM, enter SongScaffolder.</strong></p>
            <br>
            <hr>
        </section>
        <section>
            <p>SongScaffolder gives you musical information! However, it doesn't tell you <em>what to do with it.</em></p>
            <p class="lead">The truth is, <span class="font-weight-bold">there's no one way to interpret these vague results!</span></p>
            <p>...But yeah, there are some different ways you <em>could</em> interpret them. We've stuck them in the numbered links below.</p>
        </section>
        <section>
            <p></p>
            <p>We'll use the following scaffold as an example:</p>
            <br>
            <div class="row">
                <div class="col-md-0 col-lg-2"></div>
                <div class="col-md-12 col-lg-8">
                    <table id="example-scaffold-results" class="table table-striped">
                        <tbody>
                            <tr>
                                <td>Chords</td>
                                <td>7sus4, 7add11, m11</td>
                            </tr>

                            <tr>
                                <td>Genres</td>
                                <td>Drum n Bass, Space Glam Rock</td>
                            </tr>

                            <tr>
                                <td>Instruments</td>
                                <td>Bouzouki, Piano</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="col-md-0 col-lg-2"></div>
            </div>
        </section>
            <br>
        <section>
            <div class="accordion" id="myAccordion">
                <div class="card">
                    <div class="card-header" id="headingOne">
                        <h2 class="mb-0">
                            <button type="button" class="btn btn-link" data-toggle="collapse" data-target="#collapseOne"><h5>1. "I just some need ideas!"</h5></button>
                        </h2>
                    </div>
                    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#myAccordion">
                        <div class="card-body">
                            <ul>
                                <li><p>Pick and choose what you like from the scaffold! Heck, you don't have to use <em>anything</em> in it!</p></li>
                                <li><p>Maybe you're just looking for ideas and combinations you wouldn't normally think of otherwise.<span style="font-size: 1.5em;">🎨🖌️🤸‍♀️</span></p></li>
                                <li><p>Are you playing G, Em, C, and D chords all the time? Well, what if you threw in an F7sus4 chord? Or a <em>C#m11??</em> <strong>Bonkers.</strong></p></li>
                                <li><p>This approach is really helpful for sparking your imagination: the sky's the limit!</p></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header" id="headingTwo">
                        <h2 class="mb-0">
                            <button type="button" class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo"><h5>2. "I must obey the scaffold."</h5></button>
                        </h2>
                    </div>
                    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#myAccordion">
                        <div class="card-body">
                            <ul>
                                <li><p>The sky is no longer the limit.</p></li>
                                <li><p>Now, you have to use everything specified in the scaffold. But nothing's stopping you from adding <em>more</em> stuff. 😉</p></li>
                                <li><p>Do you like guitar? <strong>Go for it,</strong> throw some guitar into the mix! (As long as you've got piano and bouzouki in there too.)</p></li>
                                <li><p>Maybe you like switching from 4/4 time to 22/8 time? <strong>Heck yeah</strong> you maybe do, and nothing in the scaffold says you can't.</p></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header" id="headingThree">
                        <h2 class="mb-0">
                            <button type="button" class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseThree"><h5>3. "I MUST OBEY THE SCAFFOLD."</h5></button>
                        </h2>
                    </div>
                    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#myAccordion">
                        <div class="card-body">
                            <ul>
                                <li><p>Whatever is in the scaffold is all you can use to write a song with. <strong>No exceptions.</strong></p></li>
                                <li><p>Do you like guitar? <strong>No. Bouzouki.</strong></p></li>
                                <li><p>Oh, you don't <em>like</em> bouzoukis? Are they not <strong>good enough</strong> for you??? Maybe you prefer the <em>tangy sounds of the bağlama???</em></p></li>
                                <li><p>Go. The Scaffolder has spoken.</p></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <br>
        <section>
            <p>So you see, your results could be interpreted as a blueprint, or as a prompt, or whatever.</p>
            <p>Make SongScaffolder <em>your</em> tool: the right interpretation is the one where it works best for <em>you.</em></p>
            #CheesyInspirationalQuotes
        </section>
    </div>

    <!-- Eventually I want to remove this call to jQuery, since I think it should only be done in base.html.  -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
{% endblock %}